/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
/**
 *
 * @author ADMIN
 */
public class profile extends javax.swing.JFrame {

    public profile() {
        
        
        initComponents();
        //addImagePanel(UserIndoData.getName());
        String temp = getVerificationStatus(UserIndoData.getName());
         setVerificationLabel(temp);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        locationLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        myprofiletext = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        instagramLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        verifybutton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JoinedTreks = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        addLINK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        createdTrek = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        textArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textArea1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textArea1);
        textArea1.setBounds(130, 310, 500, 80);

        locationLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(255, 255, 255));
        locationLabel.setText("Location : ");
        locationLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(locationLabel);
        locationLabel.setBounds(20, 190, 310, 30);

        jButton4.setText("home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1325, 682, 93, 23);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jButton1.setText("HOME");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(700, 580, 140, 50);

        myprofiletext.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        myprofiletext.setForeground(new java.awt.Color(255, 255, 255));
        myprofiletext.setText("MY PROFILE");
        jPanel1.add(myprofiletext);
        myprofiletext.setBounds(20, 30, 290, 50);

        ageLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age : ");
        ageLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(ageLabel);
        ageLabel.setBounds(20, 150, 310, 33);

        instagramLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        instagramLabel.setText("instagram : ");
        jPanel1.add(instagramLabel);
        instagramLabel.setBounds(100, 600, 430, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("About me : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 320, 100, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel10.setText("Connect with me : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 570, 138, 22);

        verifybutton.setBackground(new java.awt.Color(204, 204, 204));
        verifybutton.setText("VERIFY PROFILE");
        verifybutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verifybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(verifybutton);
        verifybutton.setBounds(660, 70, 130, 30);

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name :");
        nameLabel.setToolTipText("");
        nameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(nameLabel);
        nameLabel.setBounds(20, 110, 310, 30);

        JoinedTreks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Joined Treks"
            }
        ));
        jScrollPane1.setViewportView(JoinedTreks);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 410, 130, 120);

        jButton2.setText("EDIT ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 370, 72, 23);

        addLINK.setText("ADD LINKS");
        addLINK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLINKActionPerformed(evt);
            }
        });
        jPanel1.add(addLINK);
        addLINK.setBounds(90, 640, 100, 20);

        createdTrek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "My Treks"
            }
        ));
        jScrollPane2.setViewportView(createdTrek);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(280, 410, 130, 120);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add your About Me :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 350, 160, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1080, 720);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
         
        
        
        
        
        profile.this.dispose();
        dashboard_v2 dashboard = new dashboard_v2();
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verifybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifybuttonActionPerformed
        // TODO add your handling code here:
        profile.this.dispose();
        Verification verify = new Verification();
        verify.setLocationRelativeTo(null);
        verify.setVisible(true);
    }//GEN-LAST:event_verifybuttonActionPerformed
   
    void setVerificationLabel(String txt){
        if(txt != null){
       
        }
    }
    
    String getVerificationStatus(String name){
        try {
          
            Connection con = DatabaseConnection.connect();
            String selectQuery = "SELECT verification_status FROM user_data WHERE name = ?";
            PreparedStatement stm = con.prepareStatement(selectQuery);
            stm.setString(1, name);
            
            ResultSet result = stm.executeQuery();
            if(result.next()){
                if(verification != null){
                    verification = result.getString("verification_status");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        }
         return verification;
    }
    
    private void addLINKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLINKActionPerformed
        // TODO add your handling code here:
        JDialog inputDialog = new JDialog();
        inputDialog.setLocationRelativeTo(null);
        inputDialog.setLayout(new FlowLayout());        
        javax.swing.JTextField linkTextField = new javax.swing.JTextField(20);
        javax.swing.JButton confirmButton = new javax.swing.JButton("Confirm");

        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get the link from the text field
                String link = linkTextField.getText();

                
                instagramLabel.setText("Instagram: " + link);

                // Close the input dialog
                inputDialog.dispose();
            }
        });

        inputDialog.add(new javax.swing.JLabel("Enter Instagram Link:"));
        inputDialog.add(linkTextField);
        inputDialog.add(confirmButton);
        inputDialog.pack();
        inputDialog.setVisible(true);
    }//GEN-LAST:event_addLINKActionPerformed
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JDialog AboutMe = new JDialog();
        AboutMe.setLocationRelativeTo(null);
        AboutMe.setLayout(new FlowLayout());
        javax.swing.JTextField AboutmeField = new javax.swing.JTextField(50);
        javax.swing.JButton confirmButton2 = new javax.swing.JButton("Confirm");
        confirmButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String info = AboutmeField.getText();                
                textArea1.setText(info);               
                AboutMe.dispose();
            }
        });
        AboutMe.add(new javax.swing.JLabel("Enter About You :"));
        AboutMe.add(AboutmeField);
        AboutMe.add(confirmButton2);
        AboutMe.pack();
        AboutMe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    void setFilename(String txt){
        filename = txt;
    }
     void setTable(String name){
            DefaultTableModel model =  (DefaultTableModel)JoinedTreks.getModel();
            model.setRowCount(0);
            Object[] rowData = {name};
            model.addRow(rowData);
    }
     
     void setMyTrekTable(String name) {
            DefaultTableModel model = (DefaultTableModel)createdTrek.getModel();
            model.setRowCount(0);
            Object[] rowData = {name};
            model.addRow(rowData);
    }
    
    public void setName(String name){
        
        nameLabel.setText("name : " + name);
        Name = name;
    }
  
   
    public void setAge(int Age){
        ageLabel.setText(("Age : " + Age));
    }
    
    public void setLocation(String Location){
        locationLabel.setText(("Location : " + Location));
    }
    
    private ImageIcon getImageFromDatabase(String Name) {
    try {
        Connection con = DatabaseConnection.connect();
        String selectQuery = "SELECT pfp FROM user_data WHERE name = ?";
        try (PreparedStatement statement = con.prepareStatement(selectQuery)) {
            statement.setString(1, Name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    Blob imageBlob = resultSet.getBlob("image");
                    byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                    ImageIcon imageIcon = new ImageIcon(imageBytes);
                    return imageIcon;
                }
            }
        }
    } catch (SQLException ex) {
    } finally {
        DatabaseConnection.disconnect();
    }
    return null;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JoinedTreks;
    private javax.swing.JButton addLINK;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTable createdTrek;
    private javax.swing.JLabel instagramLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel myprofiletext;
    private javax.swing.JLabel nameLabel;
    private java.awt.TextArea textArea1;
    private javax.swing.JButton verifybutton;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel JLabel;
    String Name;
    String filename;
    String verification;
}
